[workspace]
resolver = "2"
members = [
    "crates/gema-core",
    "crates/gema-wasm",
    "crates/gema-cli",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/p4ranoic0/gemapdf"

[workspace.dependencies]
lopdf = "0.36"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
flate2 = "1"
thiserror = "2"
