[package]
name = "gema-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
gema-compress = { path = "../crates/gema-compress" }
gema-edit = { path = "../crates/gema-edit" }

[[bin]]
name = "analyze"
path = "fuzz_targets/analyze.rs"
test = false
doc = false
bench = false

[[bin]]
name = "compress"
path = "fuzz_targets/compress.rs"
test = false
doc = false
bench = false

[[bin]]
name = "compress_with_control"
path = "fuzz_targets/compress_with_control.rs"
test = false
doc = false
bench = false

[[bin]]
name = "edit_text"
path = "fuzz_targets/edit_text.rs"
test = false
doc = false
bench = false
